# -*- coding: utf-8 -*-
"""cryppro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18pSz0NV6cZOSNo_XlADL8_87axfh2udc
"""

!pip install python-binance
import pandas as pd
import sqlalchemy
from binance.client import Client
from binance import BinanceSocketManager

import asyncio

api_key = "abc"
api_secret = "xyz"

client = Client(api_key, api_secret)

bsm = BinanceSocketManager(client)

socket = bsm.trade_socket('BTCUSDT')

async def main():
          while True:
                await socket.__aenter__()
                msg = await socket.recv()
                frame = createframe(msg)
                frame.to_sql('BTCUSDT', engine, if_exists='appened', index=False)
                print(frame)

def createframe(msg):
    df = pd.DataFrame([msg])
    df = df.loc[:,['s','E','p']]
    df.columns = ['symbol','Time','Price']
    df.Price = df.Price.astype(float)
    df.Time = pd.to_datetime(df.Time, unit='ms')
    return df

createframe(msg)

engine = sqlalchemy.create_engine('sqlite:///BTCUSDTstream.db')